Use "[argument]" instead of "<argument>?"
Jannyboy11/InvSee-plus-plus pull request #60
Opened 2023-05-28 15:03 UTC by fxiqval

The standards suggest this change:
![](https://github.com/Jannyboy11/InvSee-plus-plus/assets/117307779/2f76529d-940b-4262-a94b-1bcedc9971fc)

2023-05-28 21:52 UTC, Jannyboy11 commented
Should be [<argument>] then, right? Because the fish brackets indicate it is a placeholder. '[argument]' would mean the literal "argument", optionally.

2023-05-29 04:34 UTC, fxiqval commented
Yes, I forgot about the placeholder. The standards are here:
 http://courses.cms.caltech.edu/cs11/material/general/usage.html#:~:text=Optional%20arguments%20should%20always%20be,an%20argument%20is%20optional%2C%20always.

2023-05-29 08:15 UTC, Jannyboy11 commented
I think it's probably best to adhere to the usage string syntax that vanilla Minecraft itself uses as well: https://minecraft.fandom.com/wiki/Commands#Syntax (which coincidentally seems to be the same that the syntax that you're proposing).

2023-05-29 13:29 UTC, Jannyboy11 commented
You are missing the changes in the README.md by the way; the command usages are written there as well.

2023-05-30 17:12 UTC, Jannyboy11 commented on README.md
> +- `/invgive <player> <item type> [amount] [nbt tag]`
should be `[<amount>]` and `[<nbt tag>]`

2023-05-30 17:12 UTC, Jannyboy11 commented on README.md
> +- `/endergive <player> <item type> [amount] [nbt tag]`
idem

2023-05-30 17:12 UTC, Jannyboy11 commented on README.md
> +- `/invclear <player> [item type] [amount]`
`[<item type>]` `[<amount>]`

2023-05-30 17:12 UTC, Jannyboy11 commented on README.md
> +- `/enderclear <player> [item type] [amount]`
idem

2023-05-30 17:14 UTC, Jannyboy11 requested changes
The [Minecraft wiki](https://minecraft.fandom.com/wiki/Commands#Syntax) states that angle brackets (`<>`) are used for to denote placeholders, and square brackets (`[]`) are used for optional arguments. Thus, to denote a placeholder for an optional argument, `[<placeholder>]` should be used (since `[foo]` would denote that the command would accept the literal "foo" as an optional argument).

2023-06-06 19:01 UTC, Jannyboy11 commented
Do you still plan to address my requested changes, or should I make the changes myself?

2023-06-07 04:27 UTC, fxiqval commented
I will make the changes later today. So you're requesting `[optional]` or `[<optional>]` for optional arguments?

2023-06-07 08:34 UTC, Jannyboy11 commented
Either you didn't read my messages, or you are just trolling now. My earlier comments clearly state that it should be `[<argument>]` for optional arguments indicated with placeholders.

2023-06-07 08:42 UTC, Jannyboy11 commented
https://github.com/Jannyboy11/InvSee-plus-plus/commit/620c7c41c743ded67d3dec868d20c69acddc0ab0

2023-06-07 08:42 UTC, closed without merging